FROM envoyproxy/envoy:v1.15.0
COPY envoy.prod.yml /etc/envoy/envoy.yaml
# COPY solarengineer.app.crt /etc/ssl/certs/solarengineer.app.crt
# COPY solarengineer.app.rsa /etc/ssl/certs/solarengineer.app.rsa

