create:
	image-edit --change-detection OnPush --skip-tests true --standalone true --style scss

component:
	ng generate component ${dir} --standalone

image:
	ng generate component components/image/${dir} --standalone

folders:
	md src/app/projects/ui
