version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available/solarengineer.net.conf:/etc/nginx/sites-available/solarengineer.net.conf
      - ./nginx/sites-available/solarengineer.net.conf:/etc/nginx/sites-enabled/solarengineer.net.conf
      - ./nginx/config/:/etc/nginx/config/:ro
      - ./https/solarengineer.net.crt:/etc/nginx/solarengineer.net.crt
      - ./https/solarengineer.net.rsa:/etc/nginx/solarengineer.net.rsa
    ports:
      - '443:443'
      - '80:80'

  postgres:
    image: postgres:14.0
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: SolarEngineer.Root
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis
    ports:
      - "6379:6379"
