export const GetManyProjects = 'GetManyProjects'
export const GetProject = 'GetProject'
export const CreatePanel = 'CreatePanel'
export const UpdatePanel = 'UpdatePanel'
export const UpdateManyPanels = 'UpdateManyPanels'
export const CreateString = 'CreateString'
export const GetUserProject = 'GetUserProject'
export const UpdateProject = 'UpdateProject'
