export const GetManyProjects = 'GetManyProjects'
export const GetProject = 'GetProject'
export const NewProject = 'NewProject'
export const ReceiveProjectEvents = 'ReceiveProjectEvents'
export const ReceiveProjectEvent = 'ReceiveProjectEvent'
