POST http://localhost:3000/projects/2
Content-Type: application/json
#Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic29sYXJlbmdpbmVlci5kZXYiXSwiZXhwIjoxNjY3NjUxODYzLCJuYmYiOjE2Njc1NjU0NjMsImlhdCI6MTY2NzU2NTQ2MywianRpIjoiMSIsImlzcyI6InNvbGFyZW5naW5lZXIuZGV2IiwibmFtZSI6ImhhcnJ5Iiwic3ViIjoiMSJ9.9MRS9BOTeKsd06LzlhzyPOJMTBgWLQ9uWml-1FwDkJ4"
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic29sYXJlbmdpbmVlci5kZXYiXSwiZXhwIjoxNjY3Nzc5NTc0LCJuYmYiOjE2Njc2OTMxNzQsImlhdCI6MTY2NzY5MzE3NCwianRpIjoiMSIsImlzcyI6InNvbGFyZW5naW5lZXIuZGV2IiwibmFtZSI6ImhhcnJ5Iiwic3ViIjoiMSJ9.TK_rGN29wWEvv1a9pj_55EUafeigQ1JOuil67IZjpGs

{}

###

POST http://localhost:3000/projects/2/3
Content-Type: application/json
#Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic29sYXJlbmdpbmVlci5kZXYiXSwiZXhwIjoxNjY3NjUxODYzLCJuYmYiOjE2Njc1NjU0NjMsImlhdCI6MTY2NzU2NTQ2MywianRpIjoiMSIsImlzcyI6InNvbGFyZW5naW5lZXIuZGV2IiwibmFtZSI6ImhhcnJ5Iiwic3ViIjoiMSJ9.9MRS9BOTeKsd06LzlhzyPOJMTBgWLQ9uWml-1FwDkJ4"
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic29sYXJlbmdpbmVlci5kZXYiXSwiZXhwIjoxNjY3Nzc5NTc0LCJuYmYiOjE2Njc2OTMxNzQsImlhdCI6MTY2NzY5MzE3NCwianRpIjoiMSIsImlzcyI6InNvbGFyZW5naW5lZXIuZGV2IiwibmFtZSI6ImhhcnJ5Iiwic3ViIjoiMSJ9.TK_rGN29wWEvv1a9pj_55EUafeigQ1JOuil67IZjpGs

{}

###
GET http://localhost:3000/projects
Accept: application/json

###
