create:
	image-edit --change-detection OnPush --skip-tests true --standalone true --style scss

generate:
  nx generate @nrwl/angular:library grid-layout/feature/block-switch/src/lib/block-types --skipModule --standalone
