export const PROJECT_SIGNALR_TYPE = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  CREATE_MANY: 'CREATE_MANY',
  UPDATE_MANY: 'UPDATE_MANY',
  DELETE_MANY: 'DELETE_MANY',
} as const

export type ProjectEventAction = (typeof PROJECT_SIGNALR_TYPE)[keyof typeof PROJECT_SIGNALR_TYPE]
