// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Users.API.Data;

#nullable disable

namespace Users.API.Data.Migrations
{
    [DbContext(typeof(UsersContext))]
    [Migration("20230212041725_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Users.API.Entities.UserLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid ()");

                    b.Property<string>("AppUserReceivedDisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AppUserReceivedId")
                        .HasColumnType("uuid");

                    b.Property<string>("AppUserReceivedNickName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AppUserReceivedStatusEvent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AppUserReceivedStatusTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AppUserRequestedDisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AppUserRequestedId")
                        .HasColumnType("uuid");

                    b.Property<string>("AppUserRequestedNickName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AppUserRequestedStatusEvent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AppUserRequestedStatusTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("BecameFriendsTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Friends")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("UserLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
