// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Users.API.Data;

#nullable disable

namespace Users.API.Data.Migrations
{
    [DbContext(typeof(UsersContext))]
    partial class UsersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Users.API.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastActiveTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastModifiedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Users.API.Entities.UserLink", b =>
                {
                    b.Property<Guid>("AppUserRequestedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppUserReceivedId")
                        .HasColumnType("uuid");

                    b.Property<string>("AppUserReceivedDisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AppUserReceivedNickName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AppUserReceivedStatusEvent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AppUserReceivedStatusTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AppUserRequestedDisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AppUserRequestedNickName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AppUserRequestedStatusEvent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AppUserRequestedStatusTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("BecameFriendsTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Friends")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AppUserRequestedId", "AppUserReceivedId");

                    b.HasIndex("AppUserReceivedId");

                    b.ToTable("UserLinks");
                });

            modelBuilder.Entity("Users.API.Entities.UserLink", b =>
                {
                    b.HasOne("Users.API.Entities.User", "AppUserReceived")
                        .WithMany("AppUserLinksReceived")
                        .HasForeignKey("AppUserReceivedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Users.API.Entities.User", "AppUserRequested")
                        .WithMany("AppUserLinksRequested")
                        .HasForeignKey("AppUserRequestedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUserReceived");

                    b.Navigation("AppUserRequested");
                });

            modelBuilder.Entity("Users.API.Entities.User", b =>
                {
                    b.Navigation("AppUserLinksReceived");

                    b.Navigation("AppUserLinksRequested");
                });
#pragma warning restore 612, 618
        }
    }
}
