version: '3'

services:

  postgres:
    image: 'postgres:14.0'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: SolarEngineer.Root
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - ./db-data/postgres/:/var/lib/postgresql/data/
