export const PROJECT_ITEM_TYPE = {
  UNDEFINED: 'UNDEFINED',
  INVERTER: 'INVERTER',
  PANEL: 'PANEL',
  CABLE: 'CABLE',
  DISCONNECTIONPOINT: 'DISCONNECTIONPOINT',
  TRAY: 'TRAY',
  RAIL: 'RAIL',
  TRACKER: 'TRACKER',
  STRING: 'STRING',
  PANEL_LINK: 'PANEL_LINK',
  PANEL_CONFIG: 'PANEL_CONFIG',
} as const

export type ProjectItemType = typeof PROJECT_ITEM_TYPE[keyof typeof PROJECT_ITEM_TYPE]
