version: '3.9'

services:

  dotnetapi:
    image: dotnetapi:1.0.0
    ports:
      - 5000:80
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DATABASE_HOST: postgres-solarengineer-do-user-11630140-0.b.db.ondigitalocean.com
      DATABASE_PORT: 25060
      DATABASE_USERNAME: doadmin
      DATABASE_PASSWORD: AVNS_eIDAV_jplzcmCdgCWV6
      DATABASE_DATABASE: defaultdb

