global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'prometheus-net'
    static_configs:
      - targets: [host.docker.internal:5000]
      # - targets: [localhost:5000]




# scrape_configs:
# - job_name: 'otel-collector'
#   scrape_interval: 10s
#   static_configs:
#   - targets: ['otel-collector:8889']
#   - targets: ['otel-collector:8888']