export const NEARBY_DRAW_MODE = {
	TWO_SIDE_AXIS_LINES: 'TWO_SIDE_AXIS_LINES',
	CENTER_LINE_SCREEN_SIZE: 'CENTER_LINE_SCREEN_SIZE',
	CENTER_LINE_BETWEEN_TWO_ENTITIES: 'CENTER_LINE_BETWEEN_TWO_ENTITIES',
} as const

export type NearbyDrawMode = (typeof NEARBY_DRAW_MODE)[keyof typeof NEARBY_DRAW_MODE]
