generate:
	ng generate library ${name} --entry-file index.ts --project-root ${dir}

gen:
	ng generate library ${name} --entry-file index.ts



gen2:
	ng generate library ${name} --entry-file index.ts --project-root projects/auth/data-access/store

genlib:
	ng generate library ${name} --entry-file index.ts --project-root projects/auth/data-access/api

genlib2:
	ng generate library ${name} --entry-file index.ts --project-root libs/grid/data-access/api

app:
	ng generate app ${name} --project-root apps/${name}

lib:
	ng generate library ${name} --entry-file index --project-root libs/${dir}

new:
	ng new client-monorepo --no-create-application
