# https://taskfile.dev

version: '3'


vars:
  GREETING: Hello, World!
  # ng generate library @@auth/data-access/api --entry-file index.ts --project-root @@auth/data-access/api

tasks:
  lib:
      cmds:
      # - echo "{{.VAR}}"
      # - ng generate library [name]
      - ng generate library {{.CLI_ARGS}} --entry-file index.ts --project-root {{.CLI_ARGS}}
      vars:
        VAR: Hello!
  hello:
      cmds:
      - echo "{{.VAR}}"
      - echo {{.CLI_ARGS}}
      vars:
        VAR: Hello!
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
