version: '3'

services:

  reverse-proxy:
    image: nginx:1.17.10
    # container_name: reverse_proxy
    # depends_on:
    #     - users-api
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
      # - ./solarengineer.net.crt:/etc/nginx/solarengineer.net.crt
      # - ./solarengineer.net.rsa:/etc/nginx/solarengineer.net.rsa
      - ../etc/ssl/solarengineer.net/solarengineer.net.crt:/etc/nginx/solarengineer.net.crt
      - ../etc/ssl/solarengineer.net/solarengineer.net.rsa:/etc/nginx/solarengineer.net.rsa
    ports:
      - 443:443
      - 80:80

