// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Inverters     string
	Panels        string
	Projects      string
	Strings       string
	Trackers      string
	Users         string
	UsersProjects string
}{
	Inverters:     "inverters",
	Panels:        "panels",
	Projects:      "projects",
	Strings:       "strings",
	Trackers:      "trackers",
	Users:         "users",
	UsersProjects: "users_projects",
}
