/* 🤖 this file was generated by svg-to-ts */

import { AppSvgWrapper } from './build/app-svg.model.ts';

export type AppSvgWrapperNameSubset<
  T extends Readonly<AppSvgWrapper[]>
> = T[number]['name'];

export * from './build/Svg-arrow-down-small.icon';
export * from './build/Svg-arrow-up-small.icon';
export * from './build/Svg-arrow-uturn-left.icon';
export * from './build/Svg-arrow-uturn-right.icon';
export * from './build/Svg-bars-3-bottom-left.icon';
export * from './build/Svg-bars-3.icon';
export * from './build/Svg-bars-arrow-up.icon';
export * from './build/Svg-bell-slash.icon';
export * from './build/Svg-bell.icon';
export * from './build/Svg-chat-bubble-left.icon';
export * from './build/Svg-check-circle.icon';
export * from './build/Svg-chevron-double-down.icon';
export * from './build/Svg-chevron-double-left.icon';
export * from './build/Svg-chevron-double-right.icon';
export * from './build/Svg-chevron-double-up.icon';
export * from './build/Svg-chevron-down.icon';
export * from './build/Svg-chevron-up.icon';
export * from './build/Svg-cog-6-tooth.icon';
export * from './build/Svg-cog-8-tooth.icon';
export * from './build/Svg-cursor-arrow-rays.icon';
export * from './build/Svg-cursor-arrow-ripple.icon';
export * from './build/Svg-data.icon';
export * from './build/Svg-edit.icon';
export * from './build/Svg-ellipsis-vertical.icon';
export * from './build/Svg-envelope-open.icon';
export * from './build/Svg-envelope.icon';
export * from './build/Svg-folder-open.icon';
export * from './build/Svg-folder-plus.icon';
export * from './build/Svg-folder.icon';
export * from './build/Svg-github.icon';
export * from './build/Svg-google.icon';
export * from './build/Svg-inbox.icon';
export * from './build/Svg-link.icon';
export * from './build/Svg-microsoft.icon';
export * from './build/Svg-minus-circle.icon';
export * from './build/Svg-move.icon';
export * from './build/Svg-paint-brush.icon';
export * from './build/Svg-pencil-square.icon';
export * from './build/Svg-play-circle.icon';
export * from './build/Svg-play.icon';
export * from './build/Svg-plus-circle.icon';
export * from './build/Svg-push-chevron-right.icon';
export * from './build/Svg-right.icon';
export * from './build/Svg-save-outline.icon';
export * from './build/Svg-share.icon';
export * from './build/Svg-sun.icon';
export * from './build/Svg-trash.icon';
export * from './build/Svg-user-circle.icon';
export * from './build/Svg-user-minus.icon';
export * from './build/Svg-user-plus.icon';
export * from './build/Svg-users.icon';
export * from './build/Svg-wrench.icon';
export * from './build/Svg-x-circle.icon';
export * from './build/Svg-x-mark.icon';
export * from './build/app-svg.model.ts';
