/* 🤖 this file was generated by svg-to-ts */

import * as SVG_CONST from '../ts-svgs/index'
import { AppSvgWrapper } from '../ts-svgs'

export const TS_SVG = SVG_CONST

export type SvgConstType = (typeof SVG_CONST)[keyof typeof SVG_CONST]

export type AppSvgKey = keyof typeof SVG_CONST
export const APP_SVG_KEY = Object.keys(SVG_CONST) as AppSvgKey[]

export const APP_SVG_KEY_OBJ = APP_SVG_KEY.reduce((obj, key) => {
	return {
		...obj,
		[key]: key,
	}
}, {} as Record<AppSvgKey, AppSvgKey>)

export const APP_SVG: AppSvgWrapper[] = APP_SVG_KEY.map((key) => {
	return {
		name: SVG_CONST[key].name,
		data: SVG_CONST[key].data,
	} as AppSvgWrapper
})

export const getSvgWrapperByKey = (key: AppSvgKey): AppSvgWrapper => {
	return {
		name: SVG_CONST[key].name,
		data: SVG_CONST[key].data,
	} as AppSvgWrapper
}

export const getSvgByKey = (key: AppSvgKey): string => {
	return SVG_CONST[key].data
}
