module.exports = {
	darkMode: 'class',
	theme: {
		extend: {
			fontFamily: {
				sans: ['ui-sans-serif', 'system-ui'],
				serif: ['ui-serif', 'Georgia'],
				mono: ['ui-monospace', 'SFMono-Regular'],
				display: ['Oswald'],
				body: ['"Open Sans"'],
				consolas: ['"Consolas"'],
				roboto: ['"Roboto"'],
				'cascadia-code': ['"Cascadia Code"'],
				helvetica: ['"Helvetica"'],
			},
			colors: {
				primaryV2: {
					light: '#5eead4',
					DEFAULT: '#14b8a6',
					dark: '#0f766e',
				},
				secondaryV2: {
					light: '#bae6fd',
					DEFAULT: '#0ea5e9',
					dark: '#0369a1',
				},
				primary: {
					50: '#eff6ff',
					100: '#dbeafe',
					200: '#bfdbfe',
					300: '#93c5fd',
					400: '#60a5fa',
					500: '#3b82f6',
					600: '#2563eb',
					700: '#1d4ed8',
					800: '#1e40af',
					900: '#1e3a8a',
				},
				white: '#ffffff',
				black: '#000000',
				lightGlowGreen: '#b6e696',
				darkPurple: '#a95ea3',
				warmRed: '#dc3a70',
				darkBlue: '#1686cd',
				skyBlue: '#89ABE3FF',
				transparent: 'transparent',
				current: 'currentColor',
				purple: '#3f3cbb',
				midnight: '#121063',
				metal: '#565584',
				tahiti: '#3ab7bf',
				silver: '#ecebff',
				'bubble-gum': '#ff77e9',
				bermuda: '#78dcca',
			},
			translate: {
				'1/7': '14.2857143%',
				'2/7': '28.5714286%',
				'3/7': '42.8571429%',
				'4/7': '57.1428571%',
				'5/7': '71.4285714%',
				'6/7': '85.7142857%',
			},
			animation: {
				wiggle: 'wiggle 1s ease-in-out infinite',
				enter: 'enter 1s ease-in-out',
				leave: 'leave 1s ease-in-out',
			},
			keyframes: {
				wiggle: {
					'0%, 100%': { transform: 'rotate(-3deg)' },
					'50%': { transform: 'rotate(3deg)' },
				},
				enter: {
					'0%': { transform: 'translate-x-full' },
					'100%': { transform: 'translate-x-0' },
				},
				leave: {
					'0%': { transform: 'translate-x-0' },
					'100%': { transform: 'translate-x-full' },
				},
			},
		},
	},
	important: true,
	plugins: [
		require('@tailwindcss/forms'),
		require('@tailwindcss/typography'),
		require('tailwindcss-animate'),
		require('flowbite/plugin'),
		require('daisyui'),
	],
	content: ['../../.node_modules/flowbite/**/*.js'],
}
