tree:
	treee  -o tree.txt --ignore 'db-data/, bin/, obj/, node_modules/, design-app/, design-app-e2e/, web/, web-app-ssr/, storybook/, core-components/, ngrx-pull/, dist/' -l 10 -d

tree2:
	treee  -o tree.txt --ignore 'db-data/, redis-data/, bin/, obj/, node_modules/, packages/, patches/, ssl/, tmp/, tools/, design-app/, design-app-e2e/, web/, web-app-ssr/, storybook/, core-components/, ngrx-pull/, dist/' -l 4 -d


#   ├── packages
#   ├── patches
#   ├── ssl
#   ├── tmp
#   |  └── libs
#   └── tools
