name: Build and Push Web UI
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'latest'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Web UI
        run: npx nx build web-app --configuration=production
        with:
          context: src/WebUI

      - name: Build Docker image
        run: docker build -f ./apps/web-app/Dockerfile . -t solarengineer-web-ui:${{ github.event.inputs.version }}
        with:
          context: src/WebUI

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: hazzajenko/web-ui:${{ github.event.inputs.version }}

